import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import Script from 'next/script';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from '@/components/theme-provider';
import { ThemeToggle } from '@/components/theme-toggle';

const inter = Inter({ subsets: ['latin'] });

// Bound Server Actions below Netlify's function ceiling.
export const maxDuration = 55;

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://quizifyyyy.netlify.app';
const siteDescription = 'Turn lecture notes, textbook excerpts, and study documents into interactive quizzes in seconds.';

// Privacy-first analytics (Umami). The script is only injected when a website
// id is configured; the origin is already whitelisted in the CSP.
const umamiWebsiteId = process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID;
const umamiScriptUrl = process.env.NEXT_PUBLIC_UMAMI_SCRIPT_URL || 'https://cloud.umami.is/script.js';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Quizify - AI-Powered Quiz Generator',
    template: '%s | Quizify',
  },
  description: siteDescription,
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    url: '/',
    siteName: 'Quizify',
    title: 'Quizify - AI-Powered Quiz Generator',
    description: siteDescription,
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Quizify - AI-Powered Quiz Generator',
    description: siteDescription,
  },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'Quizify',
  url: siteUrl,
  applicationCategory: 'EducationalApplication',
  operatingSystem: 'Any',
  description: siteDescription,
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // The per-request CSP nonce is generated by src/proxy.ts and echoed on the
  // request as an x-nonce header, so inline scripts rendered here stay
  // CSP-compliant.
  const nonce = (await headers()).get('x-nonce') ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} min-h-screen bg-background text-foreground antialiased selection:bg-primary/20 selection:text-primary`}>
        {/* JSON-LD structured data (static, developer-authored content only) */}
        <script
          type="application/ld+json"
          nonce={nonce}
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* Umami analytics, only rendered when NEXT_PUBLIC_UMAMI_WEBSITE_ID is set */}
        {umamiWebsiteId && (
          <Script
            id="umami-analytics"
            src={umamiScriptUrl}
            data-website-id={umamiWebsiteId}
            strategy="afterInteractive"
            nonce={nonce}
          />
        )}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          nonce={nonce}
        >
          {/* Floating Theme Toggle */}
          <div className="fixed top-4 right-4 z-50">
            <ThemeToggle />
          </div>

          {/* Main Content Body */}
          <div className="relative flex min-h-screen flex-col">
            {children}
          </div>

          <Toaster />
        </ThemeProvider>

        {/* PWA: register the offline service worker once the page has loaded */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html:
              "if ('serviceWorker' in navigator) { window.addEventListener('load', function () { navigator.serviceWorker.register('/sw.js?v=3').catch(function () {}); }); }",
          }}
        />
      </body>
    </html>
  );
}
